### ISSUE TITLE
Cannot comment out in .pss

### ISSUE THREAD

**Issue by ekafyi** [eveningkid/pretty-components#2]
Hi, this is a great plugin!

Just ran across this problem when trying to print comment, eg.

```
Button {
  /** Comment here */
  border: 2px solid yellow;
}
```

I got the error: **_Module build failed: TypeError: Cannot read property 'trim' of undefined_**

Same error came up when I changed `/** Blah */` to SASS-style comment `// Blah`

Is it intentional? Anything I should change/do to troubleshoot?

Thanks!

**Comment by eveningkid** [comment]
Hi @ekaoddlass, thanks for letting me know.

This repository hasn't been updated with the latest parser for .pss files.
For now, it is recommended to use [pss-loader](https://github.com/eveningkid/pss-loader) that fallback to styled-components instead.

I'm sorry, I totally forgot to mention it on the readme file! 

If you switch to pss-loader, you'll be able to write comments using `//`.
Hope it won't be too troublesome for you so that you can still enjoy writing PSS! :)

Your feedback means a lot to me, have a nice day!

**Comment by ekafyi** [comment]
Thanks for the quick response!

I read thru the Medium tutorial but haven't got round to trying it — it looks like with pss-loader, I can access [styled-components `theme` object](https://www.styled-components.com/docs/advanced#theming)? If yes, that's awesome!

Anyway, going to try using pss-loader now. Will get back to this if I have any problem.

Cheers!

**Comment by eveningkid** [comment]
Yes, any `$variable` will actually get the value of `props.variable`.

Therefore, `$theme.primary` will fetch the value for `primary` used in your theme. :)
